config/routes.rb
Rails.application.routes.draw do
  resources :consultants

  resources :services

  resources :patients
  root "patients#index"
  
end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	validates :surname, :first_name, presence: true
	after_create :mrno

	def mrno
		update_attribute(:mrn, "P#{self.id}H")
	end
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  before_action :set_consultant, only: [:show, :edit, :update, :destroy]

  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
  end

  # GET /consultants/new
  def new
    @consultant = Consultant.new
  end

  # GET /consultants/1/edit
  def edit
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(consultant_params)

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to consultants_path, notice: 'Consultant was successfully created.' }
        format.json { render :index, status: :created, location: @consultant }
      else
        format.html { render :new }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultants/1
  # PATCH/PUT /consultants/1.json
  def update
    respond_to do |format|
      if @consultant.update(consultant_params)
        format.html { redirect_to @consultant, notice: 'Consultant was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultant }
      else
        format.html { render :edit }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant.destroy
    respond_to do |format|
      format.html { redirect_to consultants_url, notice: 'Consultant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultant
      @consultant = Consultant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultant_params
      params.require(:consultant).permit(:name)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_path, notice: 'Patient was successfully created.' }
        format.json { render :index, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:mrn, :surname, :first_name)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to services_path, notice: 'Service was successfully created.' }
        format.json { render :index, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/consultants/_form.html.erb
<%= form_for(@consultant) do |f| %>
  <% if @consultant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consultant.errors.count, "error") %> prohibited this consultant from being saved:</h2>

      <ul>
      <% @consultant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consultants/edit.html.erb
<h1>Editing Consultant</h1>

<%= render 'form' %>

<%= link_to 'Show', @consultant %> |
<%= link_to 'Back', consultants_path %>

app/views/consultants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Consultants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultants.each do |consultant| %>
      <tr>
        <td><%= consultant.name %></td>
        <td><%= link_to 'Show', consultant %></td>
        <td><%= link_to 'Edit', edit_consultant_path(consultant) %></td>
        <td><%= link_to 'Destroy', consultant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consultant', new_consultant_path %>

app/views/consultants/new.html.erb
<h1>New Consultant</h1>

<%= render 'form' %>

<%= link_to 'Back', consultants_path %>

app/views/consultants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @consultant.name %>
</p>

<%= link_to 'Edit', edit_consultant_path(@consultant) %> |
<%= link_to 'Back', consultants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Efehsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mrn %><br>
    <%= f.text_field :mrn %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>Mrn</th>
      <th>Surname</th>
      <th>First name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.mrn %></td>
        <td><%= patient.surname %></td>
        <td><%= patient.first_name %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mrn:</strong>
  <%= @patient.mrn %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @patient.surname %>
</p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.amount %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @service.amount %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>